<?php

declare(strict_types = 1);
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace Spool\Pedis;

defined('PEDIS_ROOT') || define('PEDIS_ROOT', dirname(__DIR__));
defined('DS') || define('DS', DIRECTORY_SEPARATOR);
defined('BASE_COMMANDS') || define('BASE_COMMANDS', [
    //key command
    'DEL'              => 'key',
    'DUMP'             => 'key',
    'EXISTS'           => 'key',
    'EXPIRE'           => 'key',
    'EXPIREAT'         => 'key',
    'KEYS'             => 'key',
    'MIGRATE'          => 'key',
    'MOVE'             => 'key',
    'OBJECT'           => 'key',
    'PERSIST'          => 'key',
    'PEXPIRE'          => 'key',
    'PEXPIREAT'        => 'key',
    'PTTL'             => 'key',
    'RANDOMKEY'        => 'key',
    'RENAME'           => 'key',
    'RENAMENX'         => 'key',
    'RESTORE'          => 'key',
    'SORT'             => 'key',
    'TTL'              => 'key',
    'TYPE'             => 'key',
    'SCAN'             => 'key',
    //string
    'APPEND'           => 'string',
    'BITCOUNT'         => 'string',
    'BITOP'            => 'string',
    'DECR'             => 'string',
    'DECRBY'           => 'string',
    'GET'              => 'string',
    'GETBIT'           => 'string',
    'GETRANGE'         => 'string',
    'GETSET'           => 'string',
    'INCR'             => 'string',
    'INCRBY'           => 'string',
    'INCRBYFLOAT'      => 'string',
    'MGET'             => 'string',
    'MSET'             => 'string',
    'MSETNX'           => 'string',
    'PSETEX'           => 'string',
    'SET'              => 'string',
    'SETBIT'           => 'string',
    'SETEX'            => 'string',
    'SETNX'            => 'string',
    'SETRANGE'         => 'string',
    'STRLEN'           => 'string',
    //hash
    'HDEL'             => 'hash',
    'HEXISTS'          => 'hash',
    'HGET'             => 'hash',
    'HGETALL'          => 'hash',
    'HINCRBY'          => 'hash',
    'HINCRBYFLOAT'     => 'hash',
    'HKEYS'            => 'hash',
    'HLEN'             => 'hash',
    'HMGET'            => 'hash',
    'HMSET'            => 'hash',
    'HSET'             => 'hash',
    'HSETNX'           => 'hash',
    'HVALS'            => 'hash',
    'HSCAN'            => 'hash',
    //list
    'BLPOP'            => 'list',
    'BRPOP'            => 'list',
    'BRPOPLPUSH'       => 'list',
    'LINDEX'           => 'list',
    'LINSERT'          => 'list',
    'LLEN'             => 'list',
    'LPOP'             => 'list',
    'LPUSH'            => 'list',
    'LPUSHX'           => 'list',
    'LRANGE'           => 'list',
    'LREM'             => 'list',
    'LSET'             => 'list',
    'LTRIM'            => 'list',
    'RPOP'             => 'list',
    'RPOPLPUSH'        => 'list',
    'RPUSH'            => 'list',
    'RPUSHX'           => 'list',
    //set
    'SADD'             => 'set',
    'SCARD'            => 'set',
    'SDIFF'            => 'set',
    'SDIFFSTORE'       => 'set',
    'SINTER'           => 'set',
    'SINTERSTORE'      => 'set',
    'SISMEMBER'        => 'set',
    'SMEMBERS'         => 'set',
    'SMOVE'            => 'set',
    'SPOP'             => 'set',
    'SRANDMEMBER'      => 'set',
    'SREM'             => 'set',
    'SUNION'           => 'set',
    'SUNIONSTORE'      => 'set',
    'SSCAN'            => 'set',
    //zset
    'ZADD'             => 'zset',
    'ZCARD'            => 'zset',
    'ZCOUNT'           => 'zset',
    'ZINCRBY'          => 'zset',
    'ZRANGE'           => 'zset',
    'ZRANGEBYSCORE'    => 'zset',
    'ZRANK'            => 'zset',
    'ZREM'             => 'zset',
    'ZREMRANGEBYRANK'  => 'zset',
    'ZREMRANGEBYSCORE' => 'zset',
    'ZREVRANGE'        => 'zset',
    'ZREVRANGEBYSCORE' => 'zset',
    'ZREVRANK'         => 'zset',
    'ZSCORE'           => 'zset',
    'ZUNIONSTORE'      => 'zset',
    'ZINTERSTORE'      => 'zset',
    'ZSCAN'            => 'zset',
    //pub/sub
    'PSUBSCRIBE'       => 'pub',
    'PUBLISH'          => 'pub',
    'PUBSUB'           => 'pub',
    'PUNSUBSCRIBE'     => 'pub',
    'SUBSCRIBE'        => 'pub',
    'UNSUBSCRIBE'      => 'pub',
    //transation
    'DISCARD'          => 'transation',
    'EXEC'             => 'transation',
    'MULTI'            => 'transation',
    'UNWATCH'          => 'transation',
    'WATCH'            => 'transation',
    //connection
    'AUTH'             => 'connection',
    'ECHOS'             => 'connection',
    'PING'             => 'connection',
    'QUIT'             => 'connection',
    'SELECT'           => 'connection',
    //server
    'BGREWRITEAOF'     => 'server',
    'BGSAVE'           => 'server',
    'CLIENT GETNAME'   => 'server',
    'CLIENT KILL'      => 'server',
    'CLIENT LIST'      => 'server',
    'CLIENT SETNAME'   => 'server',
    'CONFIG GET'       => 'server',
    'CONFIG RESETSTAT' => 'server',
    'CONFIG REWRITE'   => 'server',
    'CONFIG SET'       => 'server',
    'DBSIZE'           => 'server',
    'DEBUG OBJECT'     => 'server',
    'DEBUG SEGFAULT'   => 'server',
    'FLUSHALL'         => 'server',
    'FLUSHDB'          => 'server',
    'INFO'             => 'server',
    'LASTSAVE'         => 'server',
    'MONITOR'          => 'server',
    'PSYNC'            => 'server',
    'SAVE'             => 'server',
    'SHUTDOWN'         => 'server',
    'SLAVEOF'          => 'server',
    'SLOWLOG'          => 'server',
    'SYNC'             => 'server',
    'TIME'             => 'server',
]);

